[project]
name = "polymarket-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24.0",
    "pandas>=3.0.0",
    "requests>=2.28.0",
    "schedule>=1.2.2",
]
